### ISSUE TITLE
crash when running mptcpcrunch

### ISSUE THREAD

**Issue by teto** [nasa/multipath-tcp-tools#5]
```
$ mptcpcrunch client.txt
Opened file with data link type: 113
Warning: Reuse of four tuple 10.0.0.1:33782:10.0.0.2:5201
Not storing key: 14803550490012999960
Warning: Token does not match either direction!
zsh: segmentation fault (core dumped)  mptcpcrunch ~/pcaps/client_2_filtered.pcapng
```
Rename to pcap
[client.txt](https://github.com/nasa/multipath-tcp-tools/files/2924232/client.txt)

**Comment by teto** [comment]
Looking at the man, I wonder what statistics are displayed ? 
TCP throughput/goodput ? reinjections ?
```
       There are currently two modes of output that can be generated, connection-level information and subflow-level information.

       Connection-level information format
              Connection-level information includes three lines of output. The first line contains some meta information about the
              connection. The second and third lines contain information about each connection direction.  Data in all three lines
              is labeled when output with the format "LABEL: DATA".

       Subflow-level information format
              For each subflow in a connection, output three lines of output. The first line contains the subflow number. The sec‐
              ond  and  third  lines  contain statistics on each direction for the subflow. Like connection-level information, all
              data is labeled when output.
```

**Comment by jishac** [comment]
Unfortunately it is a known limitation when mptcpcrunch is passed a trace file with multiple MPTCP connections.  As noted in the man page, mptcpcrunch was intended to be run on a pcap file of a single MPTCP connection.  A looping script can be used to dump stats from a pcap file with multiple connections.  For example, this bash script:

`{ INPUT=client.pcap; mptcpsplit -l ${INPUT} | while read CONNECTION; do CONN_NUM=$(echo ${CONNECTION}|cut -d' ' -f 2); echo ${CONNECTION}; mptcpsplit -n ${CONN_NUM} ${INPUT}; mptcpcrunch -c -s outfile.pcap; done; } 2>/dev/null`

properly displays the information for each connection in the attached example pcap file.

**Comment by teto** [comment]
thanks  I will test that and reopen in case of problem.
